### ISSUE TITLE
Alternative in javamelody

### ISSUE THREAD

**Issue by evernat** [fschlag/javamelody-prometheus-exporter#2]
Hi,

Thanks for this javamelody-prometheus-exporter.
I did not know about it when a promotheus integration was added into javamelody itself, since v1.70 based on PRs by @slynn1324.
This integration is documented there:
https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#exposing-metrics-to-prometheus

I suggest to add a note about this integration as an alternative in README.md.
I will do a PR.

**Comment by fschlag** [comment]
Hi,

glad to hear that JavaMelody now has native support for prometheus!

I merged your PR, thanks for that!

This exporter is also listed in the official Prometheus documenation here: https://prometheus.io/docs/instrumenting/exporters/#other-monitoring-systems

Maybe you want to open a PR in the Prometheus documentation repository for JavaMelody ("Software exposing Prometheus metrics")? https://github.com/prometheus/docs

Happy new year!

**Comment by evernat** [comment]
I have created a PR.
Happy new year to you too.
